# Generated by Django 3.2.9 on 2021-11-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='Username', max_length=50),
        ),
    ]
