# Generated by Django 3.2.9 on 2021-11-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211115_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
